# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 21:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('review_app', '0002_remove_book_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, related_name='userReviews', to='login_app.User'),
        ),
    ]
