# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('review_app', '0003_review_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userReviews', to='login_app.User'),
        ),
    ]
